-- Helpdesk Ticket Management System — SQLite Schema
-- Phase 1 Internal IT — Generated by HDMS v1.0.0

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_name    TEXT    NOT NULL,
    department       TEXT    NOT NULL,
    issue_category   TEXT    NOT NULL,
    description      TEXT    NOT NULL,
    priority         TEXT    NOT NULL DEFAULT 'Medium'  CHECK(priority IN ('Low','Medium','High','Critical')),
    status           TEXT    NOT NULL DEFAULT 'Open'    CHECK(status IN ('Open','In Progress','Resolved','Closed')),
    resolution_notes TEXT    DEFAULT '',
    created_at       TEXT    DEFAULT (datetime('now'))
);

-- Indexes for fast filter/search queries
CREATE INDEX IF NOT EXISTS idx_status    ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_priority  ON tickets(priority);
CREATE INDEX IF NOT EXISTS idx_category  ON tickets(issue_category);
CREATE INDEX IF NOT EXISTS idx_created   ON tickets(created_at DESC);

-- Sample seed data
INSERT INTO tickets (employee_name, department, issue_category, description, priority, status, resolution_notes, created_at) VALUES
('Rahul Sharma',  'Engineering', 'VPN Issue',             'Unable to connect to company VPN from home. Getting error 602 on Windows 11.', 'High',     'In Progress', 'Checking VPN gateway logs. Resetting credentials.',    datetime('now','-2 days')),
('Ananya Iyer',   'HR',          'Password Reset',        'Forgot Windows login password after returning from leave.',                      'Medium',   'Resolved',    'Reset via Active Directory. User confirmed access.',   datetime('now','-4 days')),
('Karthik Nair',  'Finance',     'Software Installation', 'Need MS Office 2021 installed for quarterly audit work.',                        'Low',      'Open',        '',                                                    datetime('now','-3 hours')),
('Priya Menon',   'Marketing',   'Laptop Issue',          'Laptop randomly shuts down during video calls. Battery at 40% but dies.',        'Critical', 'Open',        '',                                                    datetime('now','-1 hours')),
('Suresh Kumar',  'Operations',  'Email Access',          'Cannot access shared mailbox support@company.com. Getting access denied.',       'Medium',   'Closed',      'Mailbox permissions granted. Verified access.',        datetime('now','-6 days')),
('Divya Reddy',   'Sales',       'Network Connectivity',  'Wi-Fi drops every 10-15 minutes in Meeting Room B.',                            'High',     'In Progress', 'Access point reset. Monitoring for 24h.',              datetime('now','-1 days')),
('Arjun Pillai',  'IT',          'Hardware Request',      'Requesting dual monitor setup for the new UI design project.',                   'Low',      'Open',        '',                                                    datetime('now','-5 hours')),
('Sneha Patel',   'Legal',       'Software Installation', 'Adobe Acrobat Pro needed for contract review and digital signatures.',           'High',     'Resolved',    'Acrobat Pro installed and license activated.',         datetime('now','-3 days'));
